#ifndef LEDS_H
#define LEDS_H

#include <stm32f4xx_hal.h>
#include <cmsis_os.h>

typedef enum {
    LED_START_LOWER = 0x0100,
    LED_START_UPPER = 0x0004,
    LED_FOCUS_LOWER = 0x0200,
    LED_FOCUS_UPPER = 0x0008,
    LED_INC_EXPOSURE = 0x0400,
    LED_DEC_EXPOSURE = 0x0800,
    LED_INC_CONTRAST = 0x1000,
    LED_DEC_CONTRAST = 0x2000,
    LED_ADD_ADJUSTMENT = 0x8000,
    LED_TEST_STRIP = 0x4000,
    LED_CANCEL = 0x0001,
    LED_MENU = 0x0002,

    LED_START = LED_START_LOWER | LED_START_UPPER,
    LED_FOCUS = LED_FOCUS_LOWER | LED_FOCUS_UPPER,
    LED_ILLUM_CONTROL = LED_START | LED_FOCUS,
    LED_ILLUM_ADJUST = LED_INC_EXPOSURE | LED_DEC_EXPOSURE | LED_INC_CONTRAST | LED_DEC_CONTRAST,
    LED_ILLUM_COMMANDS = LED_ADD_ADJUSTMENT | LED_TEST_STRIP | LED_CANCEL | LED_MENU,
    LED_ILLUM_ALL = LED_ILLUM_CONTROL | LED_ILLUM_ADJUST | LED_ILLUM_COMMANDS,
} led_t;

HAL_StatusTypeDef led_init(I2C_HandleTypeDef *hi2c, osMutexId_t i2c_mutex);

HAL_StatusTypeDef led_set_value(led_t led, uint8_t value);

#endif /* LEDS_H */
