#
# Custom Makefile targets
#

printalyzer-desc.dat: printalyzer.bin
	../tools/checksum.pl printalyzer.bin printalyzer-desc.dat

printalyzer-out.elf: printalyzer.elf printalyzer-desc.dat
	arm-none-eabi-objcopy --update-section .app_descriptor=printalyzer-desc.dat \
	  printalyzer.elf printalyzer-out.elf

printalyzer-out.bin: printalyzer-out.elf
	arm-none-eabi-objcopy -O binary printalyzer-out.elf "printalyzer-out.bin"
